### PR TITLE
BUILD FIX: for Windows and Linux when building static libs

### LINKED ISSUE #74: clFFT examples not building  when using the static library
This effects Windows and Linux. The problem does not seem to appear on OSX.

The link error for windows can be seen here:

https://gist.github.com/shehzan10/40126b46e111c4e2db62

The link error for Linux can be seen here:
```
[ 67%] /usr/bin/ld: ../library/libclFFT.a(lifetime.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/CMakeFiles/example_examples_fft3d.dir/build.make:87: recipe for target 'examples/examples/fft3d' failed
make[2]: *** [examples/examples/fft3d] Error 1
CMakeFiles/Makefile2:400: recipe for target 'examples/CMakeFiles/example_examples_fft3d.dir/all' failed
make[1]: *** [examples/CMakeFiles/example_examples_fft3d.dir/all] Error 2
```

This needs to be fixed before https://github.com/arrayfire/arrayfire/pull/454 can make it into our repo.

### PR DESCRIPTION
**Pull request by pavanky**
Tests, examples and other downstream binaries need `CMAKE_DL_LIBS`

- Fixes #74

### CODE REVIEW

**Comment by glehmann** [comment]
https://github.com/glehmann/clFFT/commit/61b15279e2482e083a168dcc60a86fa0cd88da28 should make the static lib usable without any extra define on the command line and https://github.com/glehmann/clFFT/commit/637c12826a91774e304e0eff2ab104d2e4014c3d cleans a bit the lib declaration in cmake.
Could you import them in your pull request?

**Comment by pavanky** [comment]
@glehmann Can you send in the merge request to our mirror ?

**Comment by bragadeesh** [comment]
Pavan - let me know if you want me to go ahead with this merge or wait.

**Comment by pavanky** [comment]
@bragadeesh We haven't tested this with the latest commits @glehmann suggested. Can you wait on this for a day or so before we can test it ?

**Comment by bragadeesh** [comment]
Ok I will wait, let me know when you are done, and then I will review and merge.

**Comment by glehmann** [comment]
@pavanky I've submitted https://github.com/arrayfire/clFFT/pull/2 for your branch. A bit strange but I don't think I can do any better, as I don't have write access to arrayfire's clfft repository.

If you're using [hub](https://hub.github.com/), you should be able to import a commit in your branch with just:

    git cherry-pick https://github.com/glehmann/clFFT/commit/61b15279e2482e083a168dcc60a86fa0cd88da28

and then just push it on github. It seems a bit simpler to me :-)

**Comment by pavanky** [comment]
@bragadeesh We have tested this branch on our end. Everything seems to work on all operating systems at this point.

**Comment by bragadeesh** [comment]
Ok I merged

**Pull request merged**
