### PR TITLE
Support for radix 17 and 19

### PR DESCRIPTION
**Pull request by pieterhijma**
Dear all,

This pull requests adds support for radix 17 and 19 sizes. The formatting of the code is kept the same as the original files. Test cases have been revised to support these radices. I've tested the contribution but since not all tests pass in the `develop` branch, I compared test cases between the `develop` branch and the `radix_17_19` branch. The results of these tests are in a separate git repository [here](https://github.com/pieterhijma/test_clFFT_radix_17_19), so the results can be reviewed or even be redone in a similar way. Finally, I also created a report with the findings on these tests that can be found [here](https://gist.github.com/pieterhijma/f9712b2f30691163811594ef418a5be6#file-test_report_clfft_radix_17_19-pdf).

Please let me know if you need more information. 

Kind regards,

Pieter Hijma

### CODE REVIEW

**Comment by bragadeesh** [comment]
@pieterhijma Thank you for your contribution, this looks great, let me do some testing on my side and get back to you

**Comment by pieterhijma** [comment]
@bragadeesh Great, thank you.

**Comment by bragadeesh** [comment]
Did basic testing, looks good, thanks

**Comment by pieterhijma** [comment]
Great, thanks.

**Pull request merged**
