### PR TITLE
Small size FFT tuning on Vega

### PR DESCRIPTION
**Pull request by stmuxa**
Below are the performance results of current patch

Tuning results

### CODE REVIEW

**Comment by stmuxa** [comment]
Hi @BenjaminCoquelle 
Pull request opened.

**Comment by tingxingdong** [comment]
basically the change is reducing loop counts from 16 to 4 for 2D.  How about for 1D? 16 is better?

**Comment by stmuxa** [comment]
Hi @tingxingdong 
Haven't saw transpose executing for 1D transforms.
Can you tell me sample config, or test name?

**Comment by tingxingdong** [comment]
transpose  is used in very large 1D. Can you try the size pow (2, 18) and above

**Comment by stmuxa** [comment]
ok, I will test.

**Comment by stmuxa** [comment]
hi @tingxingdong 
here I compared 1D FFTs

untitled

For greater sizes current tuning is not applied, because 2M > 1K * 1K (see code).

**Comment by tingxingdong** [comment]
Thank you. Then the optimization applied for both 1D and 2D, accordingly, I think it should apply to 3D, too. As 3D will break down into lower dimension. So can you remove the 2D condition and push it?

**Comment by stmuxa** [comment]
@tingxingdong 
I've tested for 3D as well. Gets faster.
Condition updated.
untitled

**Comment by tingxingdong** [comment]
good

**Pull request merged**
