### PR TITLE
Dummy commit to test PR - DO NOT MERGE

### PR DESCRIPTION
**Pull request by shehzan10**
This change is [Reviewable](https://reviewable.io/reviews/clmathlibraries/clfft/143)

### CODE REVIEW

**Comment by shehzan10** [comment]
build clMath clFFT ci

**Comment by shehzan10** [comment]
build clMath clFFT ci

**Comment by kknox** [comment]
sweet :smiley: :shipit:

**Comment by kknox** [comment]
build clMath clFFT ci

**Pull request closed without merging**
