### PR TITLE
update cmake script

### PR DESCRIPTION
**Pull request by nevion**

### CODE REVIEW

**Comment by bragadeesh** [comment]
Not sure if this is done by mistake, whats this PR about?

**Comment by nevion** [comment]
using a modern cmake script that detects paths better.  The script is extracted from cmake 3.7.2 and significantly better than what's there now. Not only that but the variables changed way back and make more sense too on top of being consistent with other projects.

**Comment by bragadeesh** [comment]
@nevion the PR breaks automatic CI checks, can you see why?
@kknox can you help review this PR?

**Comment by nevion** [comment]
FindPackageHandleStandardArgs.cmake - looks like it's trying to pull from the current directory this file (which most cmake scripts built on).

Actually FindOpenCL.cmake has been in cmake for a while, at least post 3.  Can we axe FindFFTW.cmake and FindOpenCL.cmake?

**Comment by nevion** [comment]
@bragadeesh @kknox 
Bump for axing FindOpenCL.cmake - it was added to CMake in February 2014

FFTW actually isn't upstream so excuse that from this request.

**Comment by kknox** [comment]
@nevion 
I'm OK with eliminating FindOpenCL.cmake, if the community is OK with bumping the minimum version of this project to v3.1.  It's hard to say if this helps or causes more grief to our end users.  

Lets bump the minimum version in our /develop branch and switch to using the shipping findopencl provided in v3.1.  This gives us some time to warn our customers that a change to build is coming.

I'll retarget this PR to the /develop branch, if you would like to amend the commit.

**Comment by kknox** [comment]
Somehow, the PR is not able to find opencl:
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 

Prior builds found opencl here:
-- Found OPENCL: /home/travis/build/clMathLibraries/clFFT/opencl-headers/lib/libOpenCL.so  

You may need to specify a ROOT for the find_package to look into.

**Comment by nevion** [comment]
@kknox so to even attempt to fix this - I have to muddle with the appveyor.yml.  It doesn't seem like my settings take effect on the build in question though.  Halp.

Also, the new script does not deal with the appveyor build-case very well - they did away with the OPENCL_ROOT hint (which I disagree with moderately - though it usually doesn't matter provided khronos headers and their icd loader, which are most of the time in predictable system locations - or you can specify the location variables directly).  But anyway maybe it would be better to rebase against current for FindOpenCL.cmake and prepend OPENCL_ROOT to the hint paths for finding headers/libraries.

Alternative is to update the appveyor.yml to point to both the header and lib location directly in the cmake command like so:

`cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBoost_NO_SYSTEM_PATHS=OFF -DOpenCL_INCLUDE_DIR=%OPENCL_ROOT%/include -DOpenCL_LIBRARY=%OPENCL_ROOT%/lib -DCMAKE_FIND_ROOT_PATH=%OPENCL_ROOT% %APPVEYOR_BUILD_FOLDER%/src`

**Comment by nevion** [comment]
@bragadeesh @kknox  I'll be less ambitious about this, going back to just trying to update to a current cmake script that I've retrofitted to accomidate OPENCL_ROOT (which your CI needs support for).

FYI I've also submitted the OPENCL_ROOT change to cmake upstream. https://github.com/Kitware/CMake/pull/287

**Comment by kknox** [comment]
This looks to be non-trivial; I don't know why the build would fail at FindPackageHandleStandardArgs.cmake.  Perhaps there are other solutions.

Looks like the cmake version in the container is 3.2.2, which should be new enough to have the findopencl logic you want in it.  Rather than check in a findopencl script, we remove our version and install the opencl icd where the shipping findopencl script expects to find it.  I think we have sudo privileges.  

If I may ask, where did the old script fail you?

**Comment by nevion** [comment]
@kknox The include of FindPackageHandleStandardArgs.cmake is the only tricky thing to this and will take me a few more tries till I find something that works (and the CI works with it).  I'll have to try a few more times till it's handled right.  The problem with the upstream one wrt to your automated build is it will then miss OPENCL_ROOT.

The old script fails at using common variable interfaces (includes, libraries).  The new cmake script uses the more common ones.  The benefit of the old script is i supported OPENCL_ROOT, which was a good thing.

**Comment by kknox** [comment]
@nevion I just wanted to point out that the simple fix is probably to modify .travis.yml script to [install the OpenCL ICD](https://github.com/clMathLibraries/clFFT/blob/master/.travis.yml#L7)  in the expected location FindOpenCL() looks.  We remove our copy of findopencl, and use the one built into cmake.  

This also avoids having to maintaining external code in our repo.

**Comment by nevion** [comment]
@kknox I think that's also acceptable however I'm not travis savvy enough to do that in reasonable time.  I already sunk in some time for my previous attempt (prior to the last push) and that just seem to get ignored.

**Comment by kknox** [comment]
@nevion I appreciate the effort you put into the PR, and i'm sorry it took me a while to pick up this thread.  I'll see if in the next week I can modify the .travis.yml to work with appveyor & travis.  If it works I'll close this PR.

**Comment by nevion** [comment]
whoops, by ignored I mean travis ... although conversations did lag quite a bit.  23 days encounting for the original PR. If you can do those things though, that'd be great just the same.

**Pull request closed without merging**
